# Numpy

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
# np.array
import numpy as np
a=np.array([1,2,3,45,4])
for i in a:
    if i%2==0:
        print("even")
    else:
        print("odd")
    print(i,end="=>")

In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(type(b))


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

In [9]:
np.array([1,2,3],dtype=bool)  #khud ka data type set krna

array([ True,  True,  True])

In [10]:
np.arange(1,10,2)  # similar to range but returns an array

array([1, 3, 5, 7, 9])

In [12]:
# with reshape
d = np.arange(1,13).reshape(3,4)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# np.ones and np.zeros
e = np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#np.zeros
f = np.zeros((2,3,4))   
print(f)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [15]:
# np.random
g = np.random.rand(3,4)  # 3x4 matrix with random values between 0 and 1
print(g)

[[0.57553059 0.75911818 0.40447484 0.30633446]
 [0.0274084  0.565313   0.43271552 0.40946444]
 [0.36222962 0.04070892 0.21288312 0.01355722]]


In [16]:
#np.linspace
h = np.linspace(0,1,5)  # 5 values between 0 and 1
print(h)

[0.   0.25 0.5  0.75 1.  ]


In [17]:
#np.identity
i = np.identity(4)  # 4x4 identity matrix   
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Array Attributes

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

In [ ]:
# ndim ye btata h ki kon sa array h
# a1.ndim
# a2.ndim
# a3.ndim


2

In [26]:
#shape ye row or collam bttata h
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [29]:
# size
# a1.size
# a2.size
a3.size

8

In [ ]:
# item size memory me kitna size h
a1.itemsize
a2.itemsize
a3.itemsize
# nbytes total memory size

8

In [31]:
# dtype ye data ka type btata h
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int64
float64
int64


# Changing DataType

In [ ]:
#astype ye datatype change krke memory bacha skte h
# a3.dtype
a3=a3.astype(np.int32)
a3.dtype


# Array Operation

In [38]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
b2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Scalar

In [43]:
# scalar operation ek number se sare arthmatic operator perform kr skte h
#arthmetic
b2 * 5


array([[ 60,  65,  70,  75],
       [ 80,  85,  90,  95],
       [100, 105, 110, 115]])

In [ ]:
# Relational operator ye har item se puchta h
b1>50


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# vector